In [24]:
g1 = np.array([1,0])
g2 = np.array([0.7,-0.7])
a1 = np.array([1,0])
a2 = np.array([0,-1])
a3 = np.array([1,-1])

In [30]:
A= np.vstack([g1,g2]).T
A

array([[ 1. ,  0.7],
       [ 0. , -0.7]])

In [26]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 1.        ,  1.        ],
       [-0.        , -1.42857143]])

In [27]:
#1번
np.dot(A_inv, a1)

array([ 1.,  0.])

In [28]:
#2번
np.dot(A_inv, a2)

array([-1.        ,  1.42857143])

In [29]:
#3번
np.dot(A_inv, a3)

array([ 0.        ,  1.42857143])

In [38]:
g1 = np.array([1,0])
g2 = np.array([0.7,-0.7])
g1

array([1, 0])

In [39]:
g2

array([ 0.7, -0.7])

In [47]:
np.vstack((g1,g2)).T

array([[ 1. ,  0.7],
       [ 0. , -0.7]])

In [48]:
w1 , V1 = np.linalg.eig(np.array([[1,1],[0,1]]))

In [51]:
np.diag(w1)


array([[ 1.,  0.],
       [ 0.,  1.]])

In [50]:
V1

array([[  1.00000000e+00,  -1.00000000e+00],
       [  0.00000000e+00,   2.22044605e-16]])

##### 고유 분해의 성질
- 1. 최대 N개
- 2. 